/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as QuestionRouteImport } from './routes/question'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionRoute = QuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/invite': typeof InviteRoute
  '/question': typeof QuestionRoute
  '/reveal': typeof RevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/invite': typeof InviteRoute
  '/question': typeof QuestionRoute
  '/reveal': typeof RevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/invite': typeof InviteRoute
  '/question': typeof QuestionRoute
  '/reveal': typeof RevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/home' | '/invite' | '/question' | '/reveal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/home' | '/invite' | '/question' | '/reveal'
  id: '__root__' | '/' | '/auth' | '/home' | '/invite' | '/question' | '/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  InviteRoute: typeof InviteRoute
  QuestionRoute: typeof QuestionRoute
  RevealRoute: typeof RevealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question': {
      id: '/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  InviteRoute: InviteRoute,
  QuestionRoute: QuestionRoute,
  RevealRoute: RevealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
